### ISSUE TITLE
Waiting for valorant to launch / stuck after game mode selected

### ISSUE THREAD

**Issue by Veyral** [sogoeslight/ValorantBot#3]
I did all the requirements except for the graphical settings (since it was fine when clicking play button and deathmatch)
So the first problem is the bot can't seem to find valorant after it was launched automatically by the bot (i set it to False) and it just keeps saying **Waiting for valorant to launch while the game is actually already up**
After that i decided to set the settings again for valorant to True and let the bot run while the game already up but **it just stuck after choosing deathmatch button**, from what i see in the picture its supposed to say lobby something but it doesn't seem to do that.
Any ideas as how it works? this is the first time i set this up, thanks.

**Comment by sogoeslight** [comment]
Hi, Veyral.
Yeah, I kinda forgot about launch feature since I don't use it for myself :D I will fix it in the nearest time.
About the second issue - it may be, that bot couldn't see some button because of your graphic settings. Anyway, it's pretty strange, cause on some screens it works perfectly fine, but in some cases like yours - it breaks. I'm still trying to investigate the problem in a free time;(
